import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { PrintButton } from "@/components/print-button";
import {
  agreementTitle,
  buildAgreementClauses,
  templateVersion,
} from "@/lib/agreements/template";
import type { AgreementData } from "@/lib/agreements/types";
import { formatDate } from "@/lib/format";
import type {
  Agreement,
  Profile,
  Property,
} from "@/lib/supabase/database.types";

export const metadata = { title: "Agreement document" };

export default async function AgreementDocumentPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const user = await requireUser();
  const supabase = await createClient();

  const { data: agreement } = await supabase
    .from("agreements")
    .select(
      "*, properties(*), owner:profiles!agreements_owner_id_fkey(*), operator:profiles!agreements_operator_id_fkey(*)"
    )
    .eq("id", id)
    .single();

  if (!agreement) notFound();

  const a = agreement as unknown as Agreement & {
    properties: Property;
    owner: Profile;
    operator: Profile;
  };

  // RLS already restricts rows, but guard explicitly for clarity.
  if (
    a.owner_id !== user.id &&
    a.operator_id !== user.id &&
    user.profile.role !== "admin"
  ) {
    notFound();
  }

  const data: AgreementData = {
    id: a.id,
    owner: {
      role: "owner",
      name: a.owner.full_name ?? "Owner",
      companyName: a.owner.company_name,
      email: a.owner.email,
    },
    operator: {
      role: "operator",
      name: a.operator.full_name ?? "Operator",
      companyName: a.operator.company_name,
      email: a.operator.email,
    },
    property: {
      title: a.properties.title,
      addressLine1: a.properties.address_line1,
      city: a.properties.city,
      state: a.properties.state,
      postalCode: a.properties.postal_code,
      leaseRestrictions: a.properties.lease_restrictions,
    },
    monthlyRent: Number(a.monthly_rent),
    leaseTermMonths: a.lease_term_months,
    startDate: a.start_date,
    endDate: a.end_date,
    governingLaw: a.properties.state
      ? `the State of ${a.properties.state}`
      : undefined,
    ownerSignedAt: a.owner_signed_at,
    operatorSignedAt: a.operator_signed_at,
  };

  const clauses = buildAgreementClauses(data);

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      {/* Toolbar (hidden when printing) */}
      <div className="flex items-center justify-between print:hidden">
        <Link
          href={`/proposals/${a.proposal_id}`}
          className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Back to proposal
        </Link>
        <PrintButton />
      </div>

      {/* Draft / legal-review banner */}
      <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 print:border print:bg-transparent">
        <strong>Draft template ({templateVersion()}).</strong> Generated by
        LeaseFlip for convenience. This is not legal advice — have it reviewed by
        a licensed attorney before signing.
      </div>

      {/* Document */}
      <article className="rounded-xl border bg-white p-8 leading-relaxed shadow-sm print:border-0 print:p-0 print:shadow-none">
        <header className="mb-6 border-b pb-4 text-center">
          <h1 className="text-2xl font-bold">{agreementTitle()}</h1>
          <p className="mt-1 text-xs text-muted-foreground">
            Reference {a.id} · Generated {formatDate(a.created_at)}
          </p>
        </header>

        <div className="space-y-5 text-sm">
          {clauses.map((clause) => (
            <section key={clause.heading}>
              <h2 className="mb-1 font-semibold">{clause.heading}</h2>
              {clause.body.map((p, i) => (
                <p key={i} className="mb-1 text-foreground/90">
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>

        {/* Signature blocks */}
        <div className="mt-10 grid grid-cols-2 gap-8 text-sm">
          <SignatureBlock
            label="Owner"
            name={data.owner.companyName || data.owner.name}
            signedAt={data.ownerSignedAt}
          />
          <SignatureBlock
            label="Operator"
            name={data.operator.companyName || data.operator.name}
            signedAt={data.operatorSignedAt}
          />
        </div>

        <p className="mt-8 text-center text-[11px] text-muted-foreground">
          Executed electronically via LeaseFlip pursuant to the U.S. ESIGN Act
          and UETA. This template is provided without warranty.
        </p>
      </article>
    </div>
  );
}

function SignatureBlock({
  label,
  name,
  signedAt,
}: {
  label: string;
  name: string;
  signedAt: string | null | undefined;
}) {
  return (
    <div>
      <div className="flex h-10 items-end border-b border-foreground/40">
        {signedAt && (
          <span className="pb-1 font-[cursive] text-lg italic">{name}</span>
        )}
      </div>
      <p className="mt-1 font-medium">{label}: {name}</p>
      <p className="text-xs text-muted-foreground">
        {signedAt ? `Signed electronically ${formatDate(signedAt)}` : "Unsigned"}
      </p>
    </div>
  );
}
